apiVersion: v1
data:
  grafana-datasources.yml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100

      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger:16686
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: grafana
  name: grafana-cm0
