apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.temp.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.temp.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:1.63.0
          name: jaeger
          ports:
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
      restartPolicy: Always
