apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.temp.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loki
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.temp.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: loki
    spec:
      containers:
        - image: grafana/loki:3.3.0
          name: loki
          ports:
            - containerPort: 3100
              protocol: TCP
      restartPolicy: Always
