apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.temp.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.temp.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: otel-collector
    spec:
      containers:
        - args:
            - --config=/etc/otel-collector-config.yaml
          image: otel/opentelemetry-collector-contrib:0.114.0
          name: otel-collector
          ports:
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/otel-collector-config.yaml
              name: otel-collector-cm0
              subPath: otel-collector-config.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: otel-collector-config.yaml
                path: otel-collector-config.yaml
            name: otel-collector-cm0
          name: otel-collector-cm0
