apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.temp.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.temp.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: promtail
    spec:
      containers:
        - args:
            - -config.file=/etc/promtail/config.yml
          image: grafana/promtail:3.3.0
          name: promtail
          volumeMounts:
            - mountPath: /etc/promtail/config.yml
              name: promtail-cm0
              subPath: config.yml
            - mountPath: /host/containers
              name: promtail-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: promtail-config.yml
                path: config.yml
            name: promtail-cm0
          name: promtail-cm0
        - name: promtail-claim1
          persistentVolumeClaim:
            claimName: promtail-claim1
