global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'order_service'
    static_configs:
      - targets: ['order:80']

  - job_name: 'inventory_service'
    static_configs:
      - targets: ['inventory:80']

  - job_name: 'payment_service'
    static_configs:
      - targets: ['payment:80']