global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
      
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order:80']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory:80']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment:80']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']